"use client";

import { useEffect, useMemo, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const stages=[["planning","PLAN"],["searching","SEARCH"],["sources_found","EVIDENCE"],["verifying","VERIFY"],["contradictions","CONFLICT"],["followup_search","RECHECK"],["synthesizing","SYNTHESIZE"],["complete","COMPLETE"]];
const presets=["Compare leading open-source edge AI frameworks in 2026.","How is RISC-V changing AI accelerator design?","Investigate the current state of on-device multimodal AI."];
const depthOptions=[["quick","QUICK"],["standard","STANDARD"],["deep","DEEP"],["investigative","INVESTIGATIVE"]];

function Confidence({value}){return <span className={"confidence "+(value||"low")}>{String(value||"low").toUpperCase()} CONFIDENCE</span>}
function SourceCard({source}){return <a className="sourceCard" href={source.url||"#"} target="_blank" rel="noreferrer"><div className="sourceTop"><span>{source.source_id}</span><small>{source.publisher||"WEB SOURCE"}</small></div><div className="qualityRow"><span className={"quality "+(source.quality_tier||"unknown")}>{String(source.quality_tier||"UNKNOWN").toUpperCase()}</span><b>{source.quality_score||0}/100</b></div><b>{source.title||"Untitled source"}</b><p>{source.snippet||"No snippet supplied."}</p><div className="sourceLink">OPEN SOURCE ↗</div></a>}
function ClaimCard({finding,sources}){const linked=(finding.source_ids||[]).map(id=>sources.find(s=>s.source_id===id)).filter(Boolean);return <article className={"claimCard "+finding.status}><div className="claimTop"><span>CLAIM</span><Confidence value={finding.confidence}/></div><h3>{finding.claim}</h3><div className="claimMeta"><span className={"status "+finding.status}>{finding.status.toUpperCase()}</span><span>{linked.length} evidence source{linked.length===1?"":"s"}</span></div><details><summary>EXPAND EVIDENCE & REASONING</summary><p className="reasoning">{finding.reasoning||"No additional reasoning supplied."}</p><div className="citationRow">{linked.map(s=><a key={s.source_id} href={s.url||"#"} target="_blank" rel="noreferrer">[{s.source_id}] {s.publisher||s.title}</a>)}</div></details></article>}

export default function Home(){
 const [question,setQuestion]=useState(""),[depth,setDepth]=useState("standard"),[events,setEvents]=useState([]),[result,setResult]=useState(null),[running,setRunning]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState(""),[sources,setSources]=useState(0),[conflicts,setConflicts]=useState(0),[theme,setTheme]=useState("dark");
 useEffect(()=>{const saved=localStorage.getItem("scoutai-theme")||"dark";setTheme(saved);document.documentElement.dataset.theme=saved},[]);
 function changeTheme(next){setTheme(next);localStorage.setItem("scoutai-theme",next);document.documentElement.dataset.theme=next}
async function exportPdf(){if(!result||exporting)return;setExporting(true);setError("");try{const res=await fetch(API+"/api/research/pdf",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({report:result,depth})});if(!res.ok){let detail="";try{const body=await res.json();detail=body?.detail||""}catch{}throw new Error(detail||("PDF export failed with HTTP "+res.status));}const blob=await res.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="scoutai-research-report.pdf";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(e){setError(e.message||"Unable to export PDF.")}finally{setExporting(false)}}
 const active=useMemo(()=>{let n=-1;events.forEach(e=>{const i=stages.findIndex(s=>s[0]===e.type);if(i>=0)n=Math.max(n,i)});return n},[events]);
 async function launch(){
  if(!question.trim()||running)return;setRunning(true);setEvents([]);setResult(null);setError("");setSources(0);setConflicts(0);
  try{const res=await fetch(API+"/api/research/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:question.trim(),depth})});if(!res.ok||!res.body)throw new Error("ScoutAI API returned HTTP "+res.status);const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="";
   while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const packets=buffer.split("\n\n");buffer=packets.pop()||"";for(const packet of packets){const line=packet.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const e=JSON.parse(line.slice(6));setEvents(x=>[...x,e]);if(e.type==="sources_found")setSources(e.data?.count||0);if(e.type==="contradictions")setConflicts(e.data?.count||0);if(e.type==="complete")setResult(e.data?.result||null);if(e.type==="error")setError(e.message||"Research failed.")}}}catch(e){setError(e.message||"Unable to connect to ScoutAI.")}finally{setRunning(false)}
 }
 const synthesis=result?.synthesis||{},findings=synthesis.key_findings||[],sourceList=result?.sources||[];
 return <main className={"shell "+(running?"mission-active":"")}><div className="scanline"/>
  <header className="topbar"><div className="brand"><div className="brandMark">S</div><div><div className="brandName">SCOUT<span>AI</span></div><div className="brandSub">AUTONOMOUS RESEARCH COMMAND</div></div></div><div className="topActions"><div className="themeSwitch" role="group" aria-label="Theme selection"><button className={theme==="dark"?"selected":""} onClick={()=>changeTheme("dark")}>☾ DARK</button><button className={theme==="light"?"selected":""} onClick={()=>changeTheme("light")}>☼ LIGHT</button></div><div className="status"><i/> SYSTEM ONLINE <b>v0.4</b></div></div></header>
  <section className="hero"><div className="eyebrow">◈ INTELLIGENCE CONSOLE / LIVE WEB RESEARCH</div><h1>Deploy a Research <em>Mission.</em></h1><p>ScoutAI plans, searches, verifies, challenges conflicting evidence, and turns the evidence graph into an interactive intelligence brief.</p>
   <div className="missionBox"><div className="missionHeader"><span>NEW RESEARCH MISSION</span><kbd>CTRL + ENTER</kbd></div><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey))launch()}} placeholder="What do you want ScoutAI to investigate?" disabled={running}/><div className="depthPicker"><span>RESEARCH DEPTH</span>{depthOptions.map(([value,label])=><button key={value} className={depth===value?"selected":""} onClick={()=>setDepth(value)} disabled={running}>{label}</button>)}</div><div className="missionFooter"><div className="presets">{presets.map(p=><button key={p} onClick={()=>setQuestion(p)} disabled={running}>{p.slice(0,30)}…</button>)}</div><button className="launch" onClick={launch} disabled={running||!question.trim()}>{running?"SCOUTING...":"LAUNCH MISSION ↗"}</button></div></div>
  </section>
  {(running||events.length>0||result)&&<section className="consoleGrid"><div className="panel tracePanel"><div className="panelTitle"><span>LIVE TRACE</span><small>{running?"ACTIVE":"STANDBY"}</small></div><div className="stageRail">{stages.map((s,i)=><div className={"stage "+(i<=active?"active ":"")+(i===active&&running?"current":"")} key={s[0]}><span>{String(i+1).padStart(2,"0")}</span>{s[1]}</div>)}</div><div className="eventFeed">{events.length===0&&<div className="muted">Awaiting mission telemetry…</div>}{events.map((e,i)=><div className="event" key={(e.timestamp||"x")+i}><span className="eventDot"/><div><b>{e.message}</b><small>{e.timestamp?new Date(e.timestamp).toLocaleTimeString():""}</small>{e.data?.queries&&<code>{e.data.queries.join("  •  ")}</code>}</div></div>)}</div></div><div className="sideStack"><div className="stats"><div><small>DEPTH</small><strong>{depth.toUpperCase()}</strong><span>MISSION MODE</span></div><div><small>SOURCES</small><strong>{sources||sourceList.length}</strong><span>COLLECTED</span></div><div><small>CONFLICTS</small><strong className={conflicts||result?.contradictions?.length?"warning":""}>{conflicts||result?.contradictions?.length||0}</strong><span>DETECTED</span></div><div><small>CONFIDENCE</small><strong>{String(synthesis.overall_confidence||"—").toUpperCase()}</strong><span>OVERALL</span></div></div><div className="panel protocol"><div className="panelTitle"><span>SCOUT PROTOCOL</span><small>ACTIVE</small></div>{["Plan independent research tasks","Retrieve live web evidence","Verify claims against sources","Challenge contradictions","Synthesize with citations"].map((x,i)=><div className="protocolLine" key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</div>)}</div></div></section>}
  {error&&<div className="errorBox">⚠ {error}</div>}
  {result&&<section className="intelligence"><div className="reportHeader"><div><div className="eyebrow">◈ MISSION DEBRIEF / EVIDENCE GRAPH</div><h2>INTELLIGENCE <em>BRIEF</em></h2><p>{result.question}</p></div><div className="reportActions"><Confidence value={synthesis.overall_confidence}/><button className="exportPdf" onClick={exportPdf} disabled={exporting}>{exporting?"GENERATING PDF...":"EXPORT PDF ↗"}</button></div></div>
   <section className="summary panel"><div className="panelTitle"><span>EXECUTIVE SUMMARY</span><small>SCOUT SYNTHESIS</small></div><p>{synthesis.executive_summary}</p></section>
   <div className="reportGrid"><section><div className="sectionHead"><span>01 / KEY CLAIMS</span><small>{findings.length} ANALYSED</small></div><div className="claims">{findings.map((f,i)=><ClaimCard key={i} finding={f} sources={sourceList}/>)}</div></section><aside><div className="sectionHead"><span>02 / EVIDENCE SOURCES</span><small>{sourceList.length} SOURCES</small></div><div className="sources">{sourceList.map(s=><SourceCard key={s.source_id} source={s}/>)}</div></aside></div>
   {result.contradictions?.length>0&&<section className="conflicts"><div className="sectionHead"><span>03 / CONTRADICTION MATRIX</span><small>{result.contradictions.length} CONFLICTS</small></div>{result.contradictions.map((c,i)=><details className="conflictCard" key={i} open><summary><span>⚠ {c.topic}</span><small>CONFLICT DETECTED</small></summary><div className="conflictBody"><div><label>SOURCE POSITION A</label><p>{c.claim_a}</p><span>{(c.source_a||[]).join(" · ")}</span></div><div className="vs">VS</div><div><label>SOURCE POSITION B</label><p>{c.claim_b}</p><span>{(c.source_b||[]).join(" · ")}</span></div></div><p className="conflictNote">{c.explanation}</p></details>)}</section>}
   <section className="limitations panel"><div className="panelTitle"><span>04 / LIMITATIONS</span><small>READ BEFORE DECISION</small></div>{(synthesis.limitations||[]).map((x,i)=><div key={i} className="limit">◈ {x}</div>)}</section>
  </section>}
  <footer><span>SCOUTAI // EVIDENCE BEFORE CONFIDENCE</span><span>SERPAPI × GEMMA</span></footer></main>
}